app1/urls.py
from app1.views import *
from django.urls import path

app_name='something'

urlpatterns=[
    path('mahakul/',mahakul,name='mahakul'),
]

app2/urls.py
from app2.views import *
from django.urls import path

app_name='nothing'

urlpatterns=[
    path('das/',das,name='das'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.



def mahakul(request):
    return render(request,'mahakul.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def das(request):
    return render(request,'das.html')

templates/das.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>recived the call..</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati</h1>
        <a href="{% url 'something:mahakul' %}">response</a>
    </center>
</body>
</html>

templates/mahakul.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>calling...</h1>
        <h1>How are you and what do you want</h1>
        <a href="{% url 'nothing:das' %}">click here</a>
    </center>
</body>
</html>